name: Continuous Integration
on:
  push:
    branches:
      - main
      - "EXP-**"
jobs:
  call-continuous-integration-reusable:
    uses: devops-iteration2/github-reusable-workflows/.github/workflows/ci.yml@main
  with:
    project_name: expense-backend
  secrets: inherit